weights: yolov5s.pt
cfg: /home/sameerahtalafha/Downloads/attach/yolo/Processed_Dataset/yolov5/models/yolov5s.yaml
data: /home/sameerahtalafha/Downloads/attach/yolo/Processed_Dataset/yolov5/data/mosq.yaml
hyp: /home/sameerahtalafha/Downloads/attach/yolo/Processed_Dataset/yolov5/data/hyp.scratch.yaml
epochs: 100
batch_size: 32
imgsz: 450
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 1
project: runs/train
name: yolo_mosq_det
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolo_mosq_det7
